### ISSUE TITLE
Links without Domain

### ISSUE THREAD

**Issue by viceinator** [onukura/gitbucket-embedding-plugin#3]
Is it possible to provide links just with the owner_name and repo_name?

Something like:
/root/my_repo/blob/master/any_file.cpp#L158-L162

That would be very nice!

**Comment by onukura** [comment]
@viceinator Thank you for your suggestion! That's sound nice! So I released new version which support link without domain. 

https://github.com/onukura/gitbucket-embedding-plugin/releases/tag/1.1.0
